---
- name: "deploy /etc/environment file to target server(s)"
  template:  src={{etc_environment.template}} dest={{etc_environment.dest}}
  when: etc_environment.deploy == true

- name: "deploy secrets.yml file to target server(s)"
  template:  src={{secrets_yml.template}} dest={{secrets_yml.dest}}
  when: secrets_yml.deploy == true

- name: "deploy application.yml file to target server(s)"
  template:  src={{application_yml.template}} dest={{application_yml.dest}}
  when: application_yml.deploy == true

- name: "deploy .rbenv-vars file to target server(s)"
  template:  src={{dot_rbenv_vars.template}} dest={{dot_rbenv_vars.dest}}
  when: dot_rbenv_vars.deploy == true

- name: "create symlink to .rbenv-vars file"
  file: src={{dot_rbenv_vars.dest}}
        dest={{dot_rbenv_vars.symlink_dest}}
        owner={{dot_rbenv_vars.symlink_owner}}
        group={{dot_rbenv_vars.symlink_group}}
        state=link
  when: dot_rbenv_vars.create_symlink == true

- name: "deploy database.yml to target server(s)"
  template:  src={{database_yml.template}}
             dest={{database_yml.dest}}
  when: database_yml.deploy == true

- name: "deploy newrelic.yml file to target server(s)"
  template:  src={{newrelic_yml.template}} dest={{newrelic_yml.dest}}
  when: newrelic_yml.deploy == true
