---
- file:
    path: "{{deploy_rails_config_dir}}"
    state: directory
    mode: 0755

- name: "deploy /etc/environment file to target server(s)"
  template:  src={{deploy_rails_env_vars.etc_environment.template}}
             dest={{deploy_rails_env_vars.etc_environment.dest}}
  when: deploy_rails_env_vars.etc_environment.deploy == true

- name: "deploy secrets.yml file to target server(s)"
  template:  src={{deploy_rails_env_vars.secrets_yml.template}}
             dest={{deploy_rails_env_vars.secrets_yml.dest}}
  when: deploy_rails_env_vars.secrets_yml.deploy == true

- name: "deploy application.yml file to target server(s)"
  template:  src={{deploy_rails_env_vars.application_yml.template}}
             dest={{deploy_rails_env_vars.application_yml.dest}}
  when: deploy_rails_env_vars.application_yml.deploy == true

- name: "deploy .rbenv-vars file to target server(s)"
  template:  src={{deploy_rails_env_vars.dot_rbenv_vars.template}}
             dest={{deploy_rails_env_vars.dot_rbenv_vars.dest}}
  when: deploy_rails_env_vars.dot_rbenv_vars.deploy == true

- name: "create symlink to .rbenv-vars file"
  file: src={{deploy_rails_env_vars.dot_rbenv_vars.dest}}
        dest={{deploy_rails_env_vars.dot_rbenv_vars.symlink_dest}}
        owner={{deploy_rails_env_vars.dot_rbenv_vars.symlink_owner}}
        group={{deploy_rails_env_vars.dot_rbenv_vars.symlink_group}}
        state=link
  when: deploy_rails_env_vars.dot_rbenv_vars.create_symlink == true

- name: "deploy database.yml to target server(s)"
  template:  src={{deploy_rails_env_vars.database_yml.template}}
             dest={{deploy_rails_env_vars.database_yml.dest}}
  when: deploy_rails_env_vars.database_yml.deploy == true

- name: "deploy newrelic.yml file to target server(s)"
  template:  src={{deploy_rails_env_vars.newrelic_yml.template}}
             dest={{deploy_rails_env_vars.newrelic_yml.dest}}
  when: deploy_rails_env_vars.newrelic_yml.deploy == true
